from .bridge import TheBridge
from .build import JustBuild
from .ctf import CaptureTheFlag
from .dr import Deathrun
from .drop import BlockDrop
from .ground import GroundWars
from .hide import HideAndSeek
from .murder import MurderMystery
from .party import BlockParty
from .sg import SurvivalGames
from .sky import Skywars
from .wars import TreasureWars